In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

**Feature Engineering**

In [2]:
df=pd.read_csv("Housing.csv")

In [3]:
df.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [4]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [5]:
df=df.replace({'yes':1, 'no':0})

C:\Users\umair\AppData\Local\Temp\ipykernel_31320\1166809327.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df=df.replace({'yes':1, 'no':0})

In [6]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,unfurnished
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,semi-furnished
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,unfurnished
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,furnished
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,unfurnished

In [7]:
def convert(val):
    if val=="furnished":
        return 2
    elif val=="semi-furnished":
        return 1
    elif val=="unfurnished":
        return 0

status=df['furnishingstatus'].map(convert)

In [8]:
df['furnishingstatus']=pd.DataFrame(status)

In [9]:
scale=MinMaxScaler()
df=pd.DataFrame(scale.fit_transform(df))

In [10]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1.000000,0.396564,0.6,0.333333,0.666667,1.0,0.0,0.0,0.0,1.0,0.666667,1.0,1.0
1,0.909091,0.502405,0.6,1.000000,1.000000,1.0,0.0,0.0,0.0,1.0,1.000000,0.0,1.0
2,0.909091,0.571134,0.4,0.333333,0.333333,1.0,0.0,1.0,0.0,0.0,0.666667,1.0,0.5
3,0.906061,0.402062,0.6,0.333333,0.333333,1.0,0.0,1.0,0.0,1.0,1.000000,1.0,1.0
4,0.836364,0.396564,0.6,0.000000,0.333333,1.0,1.0,1.0,0.0,1.0,0.666667,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,0.006061,0.092784,0.2,0.000000,0.000000,1.0,0.0,1.0,0.0,0.0,0.666667,0.0,0.0
541,0.001485,0.051546,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.5
542,0.000000,0.135395,0.2,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
543,0.000000,0.086598,0.4,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.0
544,0.000000,0.151203,0.4,0.000000,0.333333,1.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

In [11]:
y=pd.DataFrame(df.iloc[:,0])
X=df.drop(df.columns[0],axis=1)

In [12]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
X,y

(           1    2         3         4    5    6    7    8    9         10  \
 0    0.396564  0.6  0.333333  0.666667  1.0  0.0  0.0  0.0  1.0  0.666667
 1    0.502405  0.6  1.000000  1.000000  1.0  0.0  0.0  0.0  1.0  1.000000
 2    0.571134  0.4  0.333333  0.333333  1.0  0.0  1.0  0.0  0.0  0.666667
 3    0.402062  0.6  0.333333  0.333333  1.0  0.0  1.0  0.0  1.0  1.000000
 4    0.396564  0.6  0.000000  0.333333  1.0  1.0  1.0  0.0  1.0  0.666667
 ..        ...  ...       ...       ...  ...  ...  ...  ...  ...       ...
 540  0.092784  0.2  0.000000  0.000000  1.0  0.0  1.0  0.0  0.0  0.666667
 541  0.051546  0.4  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.000000
 542  0.135395  0.2  0.000000  0.000000  1.0  0.0  0.0  0.0  0.0  0.000000
 543  0.086598  0.4  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0  0.000000
 544  0.151203  0.4  0.000000  0.333333  1.0  0.0  0.0  0.0  0.0  0.000000

       11   12
 0    1.0  1.0
 1    0.0  1.0
 2    1.0  0.5
 3    1.0  1.0
 4    0.0  1.0
 ..   ...  ...
 540  0.0  0.0
 541  0.0  0.5
 542  0.0  0.0
 543  0.0  1.0
 544  0.0  0.0

 [545 rows x 12 columns],
             0
 0    1.000000
 1    0.909091
 2    0.909091
 3    0.906061
 4    0.836364
 ..        ...
 540  0.006061
 541  0.001485
 542  0.000000
 543  0.000000
 544  0.000000

 [545 rows x 1 columns])

**Gradien Desent with iterations**

In [14]:
def gradient_descent(X, y, learning_rate=0.01, iterations=100):
    m, n=X.shape
    theta=np.zeros((n, 1))
    for i in range(iterations):
        prediction=X@theta
        
        loss=(prediction-y)
        gradient=(1/m)*(X.T@loss)
        
        theta=theta-(learning_rate*gradient)
    return theta

theta_gd = gradient_descent(X_test, y_test)
print("Gradient Descent Parameters:\n",theta_gd)

Gradient Descent Parameters:
            0
1   0.040374
2   0.056554
3   0.028308
4   0.057301
5   0.113646
6   0.031845
7   0.044298
8   0.009222
9   0.067500
10  0.046196
11  0.051071
12  0.067279

**Normal Equation**

In [15]:
def normeqn(X,y):
    X_transpose = X.T
    X_transpose_X = np.dot(X_transpose, X)
    X_transpose_y = np.dot(X_transpose, y)
    X_with_intercept = X_transpose_X + np.eye(X_transpose_X.shape[0])
    
    theta = np.linalg.solve(X_with_intercept, X_transpose_y)
    
    return theta

theta_ne=normeqn(X_test,y_test)
print("Normal Equation Parameters:\n",theta_ne)

Normal Equation Parameters:
 [[0.20551909]
 [0.0366138 ]
 [0.13215287]
 [0.16526246]
 [0.03168497]
 [0.05020979]
 [0.02700523]
 [0.15274744]
 [0.10111696]
 [0.13330505]
 [0.07303977]
 [0.05194612]]

**Predefined Library Parameter calculation**

In [16]:
model=LinearRegression()

In [17]:
model.fit(X_train,y_train)

LinearRegression()

In [21]:
# model.predict(X_test)

In [19]:
model.intercept_

array([0.00808262])

In [20]:
print(f"The Library model's parameters are :\n{model.coef_}")

The Library model's parameters are :
[[0.29710819 0.03401493 0.28496552 0.10551251 0.03175967 0.02018587
  0.03403981 0.05955682 0.06801304 0.05863806 0.05453694 0.0364324 ]]