In [2]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [3]:
train_data=pd.read_csv("titanic_train.csv")
train_data=train_data.dropna()
train_data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [5]:
test_data=pd.read_csv("titanic_test.csv")
test_data=test_data.dropna()
test_data.head(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
14,906,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
26,918,1,"Ostby, Miss. Helene Ragnhild",female,22.0,0,1,113509,61.9792,B36,C
28,920,1,"Brady, Mr. John Bertram",male,41.0,0,0,113054,30.5000,A21,S

In [6]:
women = train_data.loc[train_data.Sex == 'female']["Survived"]
rate_women = sum(women)/len(women)
print("% of women who survived:", rate_women)

% of women who survived: 0.9318181818181818

In [7]:
men=train_data.loc[train_data.Sex=='male']["Survived"]
rate_men=sum(men)/len(men)
print("%  oof men wh survived:", rate_men)

%  oof men wh survived: 0.43157894736842106

In [8]:
y=train_data["Survived"]
features=["Pclass","Sex","Age","Parch"]
x=pd.get_dummies(train_data[features]) # substitutes the string values with numeric values
x_test=pd.get_dummies(test_data[features]) # substitutes the strings with numeric values

In [9]:
clf=RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
clf.fit(x,y)
predictions=clf.predict(x_test)

In [10]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!