In [1]:
import pandas as pd
import numpy as np

In [4]:
data= pd.read_csv("diabetes.csv")
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [13]:
from sklearn.preprocessing import Binarizer
c= Binarizer(threshold=0.5).fit(data)
d=c.transform(data)
d

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 1., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 0.],
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 0., 1., 0.]])

In [14]:
p=pd.read_csv("car.csv")
m=p.isnull

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [19]:
from sklearn.preprocessing import Normalizer
c=Normalizer(norm='max').fit_transform(data)
c

array([[0.04054054, 1.        , 0.48648649, ..., 0.00423649, 0.33783784,
        0.00675676],
       [0.01176471, 1.        , 0.77647059, ..., 0.00412941, 0.36470588,
        0.        ],
       [0.04371585, 1.        , 0.34972678, ..., 0.00367213, 0.17486339,
        0.00546448],
       ...,
       [0.04132231, 1.        , 0.59504132, ..., 0.00202479, 0.24793388,
        0.        ],
       [0.00793651, 1.        , 0.47619048, ..., 0.00276984, 0.37301587,
        0.00793651],
       [0.01075269, 1.        , 0.75268817, ..., 0.0033871 , 0.24731183,
        0.        ]])