In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("uterus data.csv")

In [3]:
df

,hsa-let-7a-1,hsa-let-7a-2,hsa-let-7a-3,hsa-let-7b,hsa-let-7c,hsa-let-7d,hsa-let-7e,hsa-let-7f-1,hsa-let-7f-2,hsa-let-7g,...,hsa-mir-942,hsa-mir-943,hsa-mir-944,hsa-mir-95,hsa-mir-9500,hsa-mir-96,hsa-mir-98,hsa-mir-99a,hsa-mir-99b,Label
0,26492.18911,25465.36414,25413.83073,6936.483940,12863.786550,3790.413109,2939.849858,18591.50639,19793.54494,19851.36717,...,4.629272,0.000000,0.611413,42.362208,0,0.960792,1439.616298,24739.791230,3973.749756,0
1,24500.58287,23922.61932,24024.29359,8966.131450,14068.397540,2580.177049,2398.297576,19594.53597,20787.24404,20572.47233,...,4.617875,0.000000,0.243046,82.473632,0,17.499317,1642.667353,22182.652520,4159.085317,0
2,30444.97479,29176.95987,29163.05397,9442.930810,13431.896350,4850.762591,3311.812965,21561.22668,23095.11125,21691.72107,...,7.827821,0.000000,0.000000,45.861822,0,3.959957,1631.133731,15497.796470,3982.150726,0
3,23039.03602,21935.53567,21919.98851,13303.380680,12468.358920,3308.876721,2038.302403,13202.67221,14083.29125,18603.33821,...,5.801179,0.000000,0.116024,73.094861,0,2.204448,558.305508,18229.626230,4514.825900,0
4,34055.04786,32850.63809,32749.36640,14646.328060,13331.152380,6518.460970,3702.655823,18622.05576,20196.64973,31044.29470,...,5.063585,0.000000,0.180842,33.455827,0,12.026013,1953.368183,17122.782610,4169.952345,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,22608.73109,21991.40263,22108.28528,9350.611663,972.678570,3203.748843,1709.128803,22881.23335,24285.39249,49341.49392,...,73.219588,0.223913,0.671739,832.732873,0,478.278413,1883.781033,1516.563525,4161.649147,1
343,25345.31481,24813.75907,24970.21881,6417.759549,3588.777229,2093.243218,2944.217396,12783.52751,13609.96089,40762.46821,...,21.436828,0.000000,0.387997,163.637688,0,340.370271,1742.397031,3816.725401,6330.751246,1
344,28786.95557,27997.70740,28146.30905,14441.395760,1706.588367,4472.779235,2362.523894,22158.05399,23744.38129,40569.36994,...,30.205104,0.000000,3.915476,579.863413,0,800.435252,1992.791049,1347.110341,4434.743178,1
345,36799.93121,35692.96525,36204.54322,17830.731100,610.842322,3393.810620,1925.847348,19208.34597,20290.34725,47388.12897,...,102.038208,0.000000,1.188795,45.570462,0,435.693243,1579.115572,592.812270,2605.837893,1
346,15864.97219,15464.69466,15573.74422,5125.200348,668.330863,3231.446029,1331.640555,17793.61722,18923.38091,60658.58979,...,15.192264,0.000000,0.000000,147.030215,0,113.941979,1235.465799,872.911434,2034.604630,1

In [4]:
df.cov()

,hsa-let-7a-1,hsa-let-7a-2,hsa-let-7a-3,hsa-let-7b,hsa-let-7c,hsa-let-7d,hsa-let-7e,hsa-let-7f-1,hsa-let-7f-2,hsa-let-7g,...,hsa-mir-942,hsa-mir-943,hsa-mir-944,hsa-mir-95,hsa-mir-9500,hsa-mir-96,hsa-mir-98,hsa-mir-99a,hsa-mir-99b,Label
hsa-let-7a-1,1.512858e+08,1.454827e+08,1.457617e+08,5.802070e+07,1.239175e+07,1.890896e+07,1.074200e+07,7.045739e+07,7.646346e+07,1.366650e+08,...,64775.028990,-63.780496,-1134.958707,7.213405e+05,0.0,1.853267e+04,5.389167e+06,1.679735e+07,-1.528659e+08,175.477429
hsa-let-7a-2,1.454827e+08,1.399749e+08,1.402409e+08,5.631018e+07,1.210718e+07,1.812853e+07,1.032409e+07,6.753833e+07,7.326190e+07,1.311290e+08,...,61421.936594,-66.269024,-1107.387905,6.868163e+05,0.0,2.153005e+04,5.144274e+06,1.624331e+07,-1.467107e+08,163.557667
hsa-let-7a-3,1.457617e+08,1.402409e+08,1.405199e+08,5.644829e+07,1.197115e+07,1.818648e+07,1.035361e+07,6.764635e+07,7.337925e+07,1.315058e+08,...,62201.795054,-64.504357,-1094.679283,6.900911e+05,0.0,2.503213e+04,5.173793e+06,1.598264e+07,-1.468041e+08,174.811827
hsa-let-7b,5.802070e+07,5.631018e+07,5.644829e+07,5.787300e+07,1.208664e+07,7.429274e+06,5.573638e+06,1.428167e+07,1.531455e+07,2.326176e+07,...,9994.187661,-145.742859,-2301.300561,-2.922950e+04,0.0,-2.780593e+05,4.428531e+05,-9.817000e+05,-3.416285e+07,112.638854
hsa-let-7c,1.239175e+07,1.210718e+07,1.197115e+07,1.208664e+07,2.714709e+07,1.558655e+06,2.626412e+06,1.717613e+06,1.445353e+06,-2.453182e+07,...,-45217.365483,-139.085118,144.230853,-3.110499e+05,0.0,-5.225664e+05,-9.816402e+05,3.380260e+07,-3.666501e+06,-999.036679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
hsa-mir-96,1.853267e+04,2.153005e+04,2.503213e+04,-2.780593e+05,-5.225664e+05,-3.069209e+02,8.333878e+03,2.660901e+05,2.939108e+05,1.352815e+06,...,1904.617724,-0.354274,41.989561,1.573497e+04,0.0,9.156683e+04,5.400880e+04,-5.665914e+05,-1.313841e+06,25.891049
hsa-mir-98,5.389167e+06,5.144274e+06,5.173793e+06,4.428531e+05,-9.816402e+05,1.318128e+06,3.730271e+05,5.539861e+06,5.986270e+06,1.219729e+07,...,10176.282670,29.824461,-6.950531,1.147196e+05,0.0,5.400880e+04,9.522870e+05,-5.526873e+05,-1.180316e+07,82.603663
hsa-mir-99a,1.679735e+07,1.624331e+07,1.598264e+07,-9.817000e+05,3.380260e+07,1.043997e+06,5.518728e+05,1.247171e+07,1.288641e+07,-1.093741e+07,...,-61837.582771,-228.210128,56.926422,-3.682154e+05,0.0,-5.665914e+05,-5.526873e+05,7.304885e+07,-4.388659e+07,-2166.699666
hsa-mir-99b,-1.528659e+08,-1.467107e+08,-1.468041e+08,-3.416285e+07,-3.666501e+06,-2.257367e+07,-1.528146e+06,-1.216644e+08,-1.310093e+08,-2.417386e+08,...,-143022.046063,756.452146,9738.749107,-1.829696e+06,0.0,-1.313841e+06,-1.180316e+07,-4.388659e+07,5.951778e+08,475.203894
Label,1.754774e+02,1.635577e+02,1.748118e+02,1.126389e+02,-9.990367e+02,7.701150e+01,6.188513e+01,1.796451e+02,2.152495e+02,1.728329e+03,...,3.106227,0.010793,0.090599,2.638192e+01,0.0,2.589105e+01,8.260366e+01,-2.166700e+03,4.752039e+02,0.135730

In [6]:
from ydata_profiling import ProfileReport

In [ ]:
report=ProfileReport(df)
report.to_file("uterus.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                        | 0/1882 [00:00<?, ?it/s]
  2%|█▍                                                                             | 33/1882 [00:00<00:18, 98.91it/s]
  3%|██                                                                             | 48/1882 [00:00<00:20, 89.27it/s]
  4%|██▉                                                                            | 70/1882 [00:00<00:21, 83.41it/s]
  6%|████▊                                                                         | 116/1882 [00:01<00:19, 89.59it/s]
  9%|███████                                                                       | 170/1882 [00:01<00:19, 86.14it/s]
 14%|██████████▋                                                                  | 260/1882 [00:02<00:09, 163.39it/s]
 18%|█████████████▉                                                               | 341/1882 [00:02<00:08, 190.64it/s]
 20%|███████████████▏                                                             | 370/1882 [00:02<00:08, 187.60it/s]
 22%|████████████████▊                                                            | 410/1882 [00:02<00:08, 179.25it/s]
 23%|█████████████████▋                                                           | 432/1882 [00:02<00:07, 184.93it/s]
 24%|██████████████████▊                                                           | 454/1882 [00:03<00:15, 94.80it/s]
 30%|██████████████████████▊                                                      | 557/1882 [00:03<00:07, 166.25it/s]
 31%|███████████████████████▊                                                     | 581/1882 [00:04<00:11, 117.31it/s]
 37%|████████████████████████████▌                                                | 697/1882 [00:04<00:05, 209.81it/s]
 39%|█████████████████████████████▉                                               | 733/1882 [00:05<00:09, 115.52it/s]
 42%|████████████████████████████████▎                                            | 790/1882 [00:05<00:08, 134.45it/s]
 43%|█████████████████████████████████▎                                           | 815/1882 [00:06<00:09, 114.91it/s]
 46%|███████████████████████████████████▍                                         | 865/1882 [00:06<00:08, 123.00it/s]
 50%|██████████████████████████████████████▋                                      | 945/1882 [00:06<00:05, 163.41it/s]
 55%|██████████████████████████████████████████                                  | 1043/1882 [00:06<00:03, 218.29it/s]
 58%|███████████████████████████████████████████▉                                | 1087/1882 [00:07<00:03, 229.10it/s]
 59%|█████████████████████████████████████████████▏                              | 1118/1882 [00:07<00:03, 222.22it/s]
 61%|██████████████████████████████████████████████▏                             | 1145/1882 [00:07<00:03, 215.65it/s]
 62%|███████████████████████████████████████████████▏                            | 1169/1882 [00:07<00:03, 201.09it/s]
 63%|████████████████████████████████████████████████                            | 1190/1882 [00:07<00:03, 179.22it/s]
 65%|█████████████████████████████████████████████████▍                          | 1224/1882 [00:08<00:05, 111.38it/s]
 68%|███████████████████████████████████████████████████▎                        | 1272/1882 [00:08<00:04, 130.87it/s]
 68%|████████████████████████████████████████████████████                        | 1288/1882 [00:08<00:04, 132.26it/s]
 69%|█████████████████████████████████████████████████████▎                       | 1304/1882 [00:09<00:06, 93.71it/s]
 74%|███████████████████████████████████████████████████████▉                    | 1386/1882 [00:09<00:03, 162.99it/s]
 75%|████████████████████████████████████████████████████████▊                   | 1406/1882 [00:09<00:03, 138.06it/s]
 76%|█████████████████████████████████████████████████████████▍                  | 1422/1882 [00:09<00:03, 127.26it/s]
 76%|█████████████████████████████████████████████████████████▉                  | 1436/1882 [00:10<00:04, 106.10it/s]
 78%|███████████████████████████████████████████████████████████▍                | 1472/1882 [00:10<00:03, 122.28it/s]